CREATE TABLE teams(
  chapter    VARCHAR(20) PRIMARY KEY,
  team_name  VARCHAR(20) NOT NULL
);

-- Adding all the teams to the teams table
INSERT INTO teams VALUES
  ('Kappa Kappa Gamma', 'Iowa State Greek Community'),
  ('Delta Tau Delta', 'Iowa State Greek Community'),
  ('Phi Beta Chi', 'Iowa State Greek Community'),
  ('Delta Zeta', 'Iowa State Greek Community'),
  ('Sigma Chi', 'Iowa State Greek Community'),
  ('Adelante', 'Iowa State Greek Community'),
  ('Alpha Kappa Lambda', 'Iowa State Greek Community'),
  ('Kappa Alpha Theta', 'Iowa State Greek Community'),
  ('Pi Kappa Alpha', 'Iowa State Greek Community'),
  ('Theta Chi', 'Iowa State Greek Community'),
  ('Alpha Gamma Delta', 'Iowa State Greek Community'),
  ('Alpha Gamma Rho', 'Iowa State Greek Community'),
  ('Phi Kappa Theta', 'Iowa State Greek Community'),
  ('Alpha Sigma Kappa', 'Iowa State Greek Community'),
  ('Kappa Delta', 'Iowa State Greek Community'),
  ('Phi Delta Theta', 'Iowa State Greek Community'),
  ('Delta Chi', 'Iowa State Greek Community'),
  ('Delta Delta Delta', 'Iowa State Greek Community'),
  ('Phi Kappa Psi', 'Iowa State Greek Community'),
  ('Triangle', 'Iowa State Greek Community'),
  ('Chi Phi', 'Iowa State Greek Community'),
  ('Alpha Delta Pi', 'Iowa State Greek Community'),
  ('Sigma Pi', 'Iowa State Greek Community'),
  ('Delta Lambda Phi', 'Iowa State Greek Community'),
  ('Alpha Chi Omega', 'Iowa State Greek Community'),
  ('Alpha Tau Omega', 'Iowa State Greek Community'),
  ('Beta Sigma Psi', 'Iowa State Greek Community'),
  ('Gamma Phi Beta', 'Iowa State Greek Community'),
  ('Phi Gamma Delta', 'Iowa State Greek Community'),
  ('Delta Sigma Phi', 'Iowa State Greek Community'),
  ('Gamma Rho Lambda', 'Iowa State Greek Community'),
  ('Alpha Omicron Pi', 'Iowa State Greek Community'),
  ('FarmHouse', 'Iowa State Greek Community'),
  ('Kappa Sigma', 'Iowa State Greek Community'),
  ('Sigma Kappa', 'Iowa State Greek Community'),
  ('Tau Kappa Epsilon', 'Iowa State Greek Community'),
  ('Theta Delta Chi', 'Iowa State Greek Community'),
  ('Chi Omega', 'Iowa State Greek Community'),
  ('Delta Upsilon', 'Iowa State Greek Community'),
  ('Lambda Chi Alpha', 'Iowa State Greek Community'),
  ('Pi Beta Phi', 'Iowa State Greek Community'),
  ('Alpha Sigma Phi', 'Iowa State Greek Community'),
  ('Pi Kappa Phi', 'Iowa State Greek Community'),
  ('Alpha Phi', 'Iowa State Greek Community'),
  ('Sigma Phi Epsilon', 'Iowa State Greek Community'),
  ('ACACIA', 'Iowa State Greek Community');

CREATE TABLE event_roster(
  id          CHAR(20)    PRIMARY KEY,
  isu_id      VARCHAR(9)  NOT NULL,
  net_id      VARCHAR(20) NOT NULL,
  first_name  VARCHAR(20) NOT NULL,
  last_name   VARCHAR(20) NOT NULL,
  chapter     VARCHAR(20) NOT NULL REFERENCES teams(chapter),
  events      TEXT[]      NOT NULL DEFAULT Array[]::TEXT[] -- array of events this person has checked in to
);
